
kind: Service
apiVersion: v1
metadata:
  name: backend-2
spec:
  selector:
    app: backend-2
  ports:
    - port: 8080 # Default port for image

---

kind: ReplicaSet
apiVersion: extensions/v1beta1
metadata:
   name: backend-2
spec:
   replicas: 2
   selector:
     matchLabels:
       app: backend-2
   template:
     metadata:
       labels:
         app: backend-2
     spec:
       containers:
       - name: backend-2
         image: kaleeswarankaruppusamy/e2esystem:kubia7
         imagePullPolicy: "Always"
         ports:
         - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpas-backend-2
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: backend-2
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50